### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'function' and 'int'

### ISSUE THREAD

**Issue by colejensen** [evogytis/baltic#22]
Hello,

I'm trying to plot a tree using this line of code `loc_tree.plotPoints(ax, x_attr=x_attr, y_attr=y_attr, size=s_func, colour=c_func, zorder=z_func)` where everything is defined. The code is one 187 of this [script ](https://github.com/colejensen/sarscov2/blob/master/scripts/baltic_explodeJSON.py)using this [input tree.](https://github.com/colejensen/sarscov2/blob/master/auspice/update2.json) I get this error as a response:

> Traceback (most recent call last):
  File "C:/Users/28Cha/sarscvo2/scripts/baltic_explodeJSON.py", line 187, in <module>
    loc_tree.plotPoints(ax, x_attr=x_attr, y_attr=y_attr, size=s_func, colour=c_func, zorder=z_func)
  File "C:\Users\28Cha\Documents\Python\venv\lib\site-packages\baltic\baltic.py", line 780, in plotPoints
    ax.scatter(outline_xs,outline_ys,s=outline_sizes,facecolor=outline_colours,edgecolor='none',zorder=zorder-1,**kwargs) ## put a circle at each tip
TypeError: unsupported operand type(s) for -: 'function' and 'int'

If I comment out line 187 and try to use the outline points, I get the same error. 

I was wondering if anyone had any suggestions. If it makes a difference, I am using version 0.1.2.

**Comment by gkarthik** [comment]
Hello @colejensen, could you run the same line except without the zorder argument and see if this error persists? 
```
loc_tree.plotPoints(ax, x_attr=x_attr, y_attr=y_attr, size=s_func, colour=c_func)
```

My line of thinking is that the error is in `zorder-1` where zorder is the lambda function that is passed if it is not `None`.

**Comment by colejensen** [comment]
Specifying the values in the function instead of having them refer back to present values worked! Thank you!
