### ISSUE TITLE
Tree regex tricky to use

### ISSUE THREAD

**Issue by ViralVerity** [evogytis/baltic#30]
The tree regex has a hard coded ".lower" (line 1274) so it makes it difficult to customise the treestring_regex for case sensitive stuff. 

Eg dendropy will write a nexus file starting with "TREE 1", so the treestring regex needs customising, but to get baltic to find the tree string,  you have to give a regex of "tree [0-9]" because of that hard-coded lower. It's not the end of the world, but it does lead to some frustration when a custom regex fails for no discernible reason.

I don't know what the solution is tbh, but thought I should flag it as a user interface thing

**Comment by evogytis** [comment]
Hi Verity, 

sorry it took so long to address this. The latest commit 8af3a8f should have fixed this issue.
