### ISSUE TITLE
Ascending branch sort?

### ISSUE THREAD

**Issue by barneypotter24** [evogytis/baltic#33]
I made the controversial decision to try to sort my tree in ascending order, and in doing so I noticed that changing the `descending` flag of the `sortBranches` function didn't change my tree at all, as it was always in descending order. 
A little digging led me to this line
https://github.com/evogytis/baltic/blob/cdfcbd84b93be6edc7c4447c74a796d84c282f78/baltic/baltic.py#L349
which seems like it should be modified to 

```
mod=-1 if descending else 1
```
Making the change locally did the trick after running the line `ll.sortBranches(descending=False)` (screenshot below):
Apologies for not submitting this as a PR, my on-save formatter made a disaster of `baltic.py` so this seemed like a better way to submit this.

![image](https://user-images.githubusercontent.com/14949788/230060774-0b3af446-b155-40eb-8ac6-5f47da403ee2.png)

**Comment by evogytis** [comment]
Ouch, that's embarassing :D Thanks for spotting this.

**Comment by evogytis** [comment]
Hi Barney,

this issue should be fixed as of 8af3a8f. Sorry it took so long to address :)

**Comment by evogytis** [comment]
This is the main branch where baltic receives updates and from which PyPI sources the latest version.

**Comment by evogytis** [comment]
I don't think I can answer that question and I'll ask that you stop posting here because this is not the right medium for it.
